# Generated by Django 5.2 on 2025-09-05 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="invoice",
            old_name="notes",
            new_name="customer_notes",
        ),
        migrations.RenameField(
            model_name="invoice",
            old_name="date",
            new_name="invoice_date",
        ),
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="notes",
            new_name="customer_notes",
        ),
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="date",
            new_name="expiry_date",
        ),
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="due_date",
            new_name="invoice_date",
        ),
        migrations.RenameField(
            model_name="proformainvoice",
            old_name="proforma_number",
            new_name="invoice_number",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="delivery_date",
        ),
        migrations.RemoveField(
            model_name="deliverychallan",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="invoice",
            name="due_date",
        ),
        migrations.RemoveField(
            model_name="proformainvoice",
            name="amount",
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="challan_type",
            field=models.CharField(
                choices=[
                    ("liquid_gas", "Supply of Liquid Gas"),
                    ("job_work", "Job work"),
                    ("approval", "Supply on Approval"),
                    ("others", "Others"),
                ],
                default="others",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="deliverychallan",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="invoice",
            name="files",
            field=models.ManyToManyField(blank=True, to="core.customerdocument"),
        ),
        migrations.AddField(
            model_name="invoice",
            name="order_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="invoice",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="invoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="adjustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="project_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="salesperson",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="tax_percentage",
            field=models.CharField(
                choices=[
                    ("0", "0%"),
                    ("5", "5%"),
                    ("12", "12%"),
                    ("18", "18%"),
                    ("28", "28%"),
                ],
                default="0",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="tax_type",
            field=models.CharField(
                choices=[("TDS", "TDS"), ("TCS", "TCS")], default="TDS", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="proformainvoice",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="deliverychallan",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("sent", "Sent"),
                    ("accepted", "Accepted"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="quote",
            name="tax_type",
            field=models.CharField(
                choices=[
                    ("TDS", "TDS"),
                    ("TCS", "TCS"),
                    ("TDS", "TDS"),
                    ("TCS", "TCS"),
                ],
                default="TDS",
                max_length=3,
            ),
        ),
        migrations.CreateModel(
            name="Bill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bill_number", models.CharField(max_length=50, unique=True)),
                ("reference_number", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("UNPAID", "Unpaid"),
                            ("PARTIAL", "Partial"),
                            ("DRAFT", "Draft"),
                        ],
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                ("bill_date", models.DateField()),
                ("due_date", models.DateField()),
                ("notes", models.TextField(blank=True)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "files",
                    models.ManyToManyField(blank=True, to="core.customerdocument"),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bills",
                        to="core.vendor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BillItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "bill",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.bill",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliveryChallanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_challan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.deliverychallan",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="InvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.invoice",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProformaInvoiceItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "proforma_invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.proformainvoice",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
