# Generated by Django 5.2 on 2025-08-27 11:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_item_vendor_deliverychallan_inventoryadjustment_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="customer_documents/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlsx",
                                ]
                            )
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="phone",
            new_name="billing_fax",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="name",
            new_name="display_name",
        ),
        migrations.RenameField(
            model_name="customer",
            old_name="address",
            new_name="remarks",
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_attention",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_pin_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_street1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="billing_street2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="currency",
            field=models.CharField(
                choices=[
                    ("AED", "AED"),
                    ("AUD", "AUD"),
                    ("BND", "BND"),
                    ("CAD", "CAD"),
                    ("CNY", "CNY"),
                    ("EUR", "EUR"),
                    ("GBP", "GBP"),
                    ("INR", "INR"),
                    ("JPY", "JPY"),
                    ("SAR", "SAR"),
                    ("USD", "USD"),
                    ("ZAR", "ZAR"),
                ],
                default="INR",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="customer",
            name="customer_type",
            field=models.CharField(
                choices=[("business", "Business"), ("individual", "Individual")],
                default="business",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="mobile",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="opening_balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="pan",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms",
            field=models.CharField(
                choices=[
                    ("due_on_receipt", "Due on Receipt"),
                    ("net_7", "Net 7"),
                    ("net_15", "Net 15"),
                    ("net_30", "Net 30"),
                    ("net_45", "Net 45"),
                ],
                default="due_on_receipt",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="salutation",
            field=models.CharField(
                blank=True,
                choices=[("dr", "Dr"), ("mr", "Mr"), ("ms", "Ms"), ("mrs", "Mrs")],
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_attention",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_country",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_fax",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_pin_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_street1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="shipping_street2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="customer",
            name="tags",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="customer",
            name="work_phone",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.CreateModel(
            name="ContactPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "salutation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dr", "Dr"),
                            ("mr", "Mr"),
                            ("ms", "Ms"),
                            ("mrs", "Mrs"),
                        ],
                        max_length=5,
                        null=True,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("work_phone", models.CharField(blank=True, max_length=50)),
                ("mobile", models.CharField(blank=True, max_length=50)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contact_persons",
                        to="core.customer",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="customer",
            name="documents",
            field=models.ManyToManyField(blank=True, to="core.customerdocument"),
        ),
    ]
