# Generated by Django 5.2 on 2025-08-29 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_customerdocument_rename_phone_customer_billing_fax_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quote",
            old_name="notes",
            new_name="customer_notes",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="date",
            new_name="expiry_date",
        ),
        migrations.RenameField(
            model_name="quote",
            old_name="valid_until",
            new_name="quote_date",
        ),
        migrations.RemoveField(
            model_name="quote",
            name="amount",
        ),
        migrations.AddField(
            model_name="quote",
            name="adjustment",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quote",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name="quote",
            name="project_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quote",
            name="reference_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="quote",
            name="salesperson",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="quote",
            name="subject",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="quote",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="quote",
            name="tax_percentage",
            field=models.CharField(
                choices=[
                    ("0", "0%"),
                    ("5", "5%"),
                    ("12", "12%"),
                    ("18", "18%"),
                    ("28", "28%"),
                ],
                default="0",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="tax_type",
            field=models.CharField(
                choices=[("TDS", "TDS"), ("TCS", "TCS")], default="TDS", max_length=3
            ),
        ),
        migrations.AddField(
            model_name="quote",
            name="terms_and_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="quote",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name="QuoteItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.item"
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_details",
                        to="core.quote",
                    ),
                ),
            ],
        ),
    ]
